Fix linter once more

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -36,5 +36,6 @@ jobs:
         run: |
           dirs_with_missing_script=$(find scripts -maxdepth 1 -mindepth 1 -type d \! -exec test -f '{}'/script.py \; -print)
           if [[ $dirs_with_missing_script ]]; then
-          echo "::setFailed missing 'script.py' in ${dirs_with_missing_script//$'\n'/, }"
+            echo "::error missing 'script.py' in ${dirs_with_missing_script//$'\n'/, }"
+            exit 1
           fi
